name: Doxygen Run

on: push
jobs:
  run-doxygen:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.8
        with:
          working-directory: 'docs/'
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          publish_dir: ./docs/html
          
